from backend.fileio import db_host, sensitive_data

TICKERS = ['abt', 'abbv', 'acn', 'ace', 'adbe', 'adt', 'aap',
           'aes', 'aet', 'afl', 'amg', 'a', 'gas', 'apd', 'arg',
           'akam', 'aa', 'agn', 'alxn', 'alle', 'ads', 'all', 'altr',
           'mo', 'amzn', 'aee', 'aal', 'aep', 'axp', 'aig', 'amt',
           'amp', 'abc', 'ame', 'amgn', 'aph', 'apc', 'adi', 'aon',
           'apa', 'aiv', 'amat', 'adm', 'aiz', 't', 'adsk', 'adp', 'an',
           'azo', 'avgo', 'avb', 'avy', 'bhi', 'bll', 'bac', 'bk', 'bcr',
           'bxlt', 'bax', 'bbt', 'bdx', 'bbby', 'brk-b', 'bby', 'blx',
           'hrb', 'ba', 'bwa', 'bxp', 'bsk', 'bmy', 'brcm', 'bf-b',
           'chrw', 'ca', 'cvc', 'cog', 'cam', 'cpb', 'cof', 'cah', 'hsic',
           'kmx', 'ccl', 'cat', 'cbg', 'cbs', 'celg', 'cnp', 'ctl', 'cern',
           'cf', 'schw', 'chk', 'cvx', 'cmg', 'cb', 'ci', 'xec', 'cinf',
           'ctas', 'csco', 'c', 'ctxs', 'clx', 'cme', 'cms', 'coh', 'ko',
           'cce', 'ctsh', 'cl', 'cmcsa', 'cma', 'csc', 'cag', 'cop', 'cnx',
           'ed', 'stz', 'glw', 'cost', 'cci', 'csx', 'cmi', 'cvs', 'dhi',
           'dhr', 'dri', 'dva', 'de', 'dlph', 'dal', 'xray', 'dvn', 'do',
           'dtv', 'dfs', 'disca', 'disck', 'dg', 'dltr', 'd', 'dov', 'dow',
           'dps', 'dte', 'dd', 'duk', 'dnb', 'etfc', 'emn', 'etn', 'ebay',
           'ecl', 'eix', 'ew', 'ea', 'emc', 'emr', 'endp', 'esv', 'etr',
           'eog', 'eqt', 'efx', 'eqix', 'eqr', 'ess', 'el', 'es', 'exc',
           'expe', 'expd', 'esrx', 'xom', 'ffiv', 'fb', 'fast', 'fdx', 'fis',
           'fitb', 'fslr', 'fe', 'fsiv', 'flir', 'fls', 'flr', 'fmc', 'fti',
           'f', 'fosl', 'ben', 'fcx', 'ftr', 'gme', 'gps', 'grmn', 'gd', 'ge',
           'ggp', 'gis', 'gm', 'gpc', 'gnw', 'gild', 'gs', 'gt', 'googl', 'goog',
           'gww', 'hal', 'hbi', 'hog', 'har', 'hrs', 'hig', 'has', 'hca', 'hcp',
           'hcn', 'hp', 'hes', 'hpq', 'hd', 'hon', 'hrl', 'hsp', 'hst', 'hcbk',
           'hum', 'hban', 'itw', 'ir', 'intc', 'ice', 'ibm', 'ip', 'ipg', 'iff',
           'intu', 'isrg', 'ivz', 'irm', 'jec', 'jbht', 'jnj', 'jci', 'joy', 'jpm',
           'jnpr', 'ksu', 'k', 'key', 'gmcr', 'kmb', 'kim', 'kmi', 'klac', 'kss',
           'krft', 'kr', 'lb', 'lll', 'lh', 'lrcx', 'lm', 'leg', 'len', 'lvlt',
           'luk', 'lly', 'lnc', 'lltc', 'lmt', 'l', 'low', 'lyb', 'mtb', 'mac',
           'm', 'mnk', 'mro', 'mpc', 'mar', 'mmc', 'mlm', 'mas', 'ma', 'mat',
           'mkc', 'mcd', 'mhfi', 'mck', 'mjn', 'mmv', 'mdt', 'mrk', 'met',
           'kors', 'mchp', 'mu', 'msft', 'mhk', 'tap', 'mdlz', 'mon', 'mnst',
           'mco', 'ms', 'mos', 'msi', 'mur', 'myl', 'ndaq', 'nov', 'navi',
           'ntap', 'nflx', 'nwl', 'nfx', 'nem', 'nwsa', 'nee', 'nlsn',
           'nke', 'ni', 'ne', 'nbl', 'jwn', 'nsc', 'ntrs', 'noc', 'nrg',
           'nue', 'nvda', 'orly', 'oxy', 'omc', 'oke', 'orcl', 'oi', 'pcar',
           'pll', 'ph', 'pdco', 'payx', 'pnr', 'pbct', 'pom', 'pep', 'pki',
           'prgo', 'pfe', 'pcg', 'pm', 'psx', 'pnw', 'pxd', 'pbi', 'pcl',
           'pnc', 'rl', 'ppg', 'ppl', 'px', 'pcp', 'pcln', 'pfg', 'pg',
           'pgr', 'pld', 'pru', 'peg', 'psa', 'phm', 'pvh', 'qrvo', 'pwr',
           'qcom', 'dgx', 'rrc', 'rtn', 'o', 'rht', 'regn', 'rf', 'rsg',
           'rai', 'rhi', 'rok', 'col', 'rop', 'rost', 'rlc', 'r', 'crm',
           'sndk', 'scg', 'slb', 'sni', 'stx', 'see', 'sre', 'shw', 'sial',
           'spg', 'swks', 'slg', 'sjm', 'sna', 'so', 'luv', 'swn', 'se',
           'stj', 'swk', 'spls', 'sbux', 'hot', 'stt', 'srcl', 'syk', 'sti',
           'symc', 'syy', 'trow', 'tgt', 'tel', 'te', 'tgna', 'thc', 'tdc',
           'tso', 'txn', 'txt', 'hsy', 'trv', 'tmo', 'tif', 'twx', 'twc',
           'tjk', 'tmk', 'tss', 'tsco', 'rig', 'trip', 'foxa', 'tsn',
           'tyc', 'ua', 'unp', 'unh', 'ups', 'uri', 'utx', 'uhs', 'unm',
           'urbn', 'vfc', 'vlo', 'var', 'vtr', 'vrsn', 'vz', 'vrtx', 'viab',
           'v', 'vno', 'vmc', 'wmt', 'wba', 'dis', 'wm', 'wat', 'antm', 'wfc',
           'wdc', 'wu', 'wy', 'whr', 'wfm', 'wmb', 'wec', 'wyn', 'wynn', 'xel',
           'xrx', 'xlnx', 'xl', 'xyl', 'yhoo', 'yum', 'zbh', 'zion', 'zts']

DB_NAME = 'algotaf'

USERNAME = sensitive_data.USERNAME
PASSWORD = sensitive_data.PASSWORD
HOSTNAME = db_host.DB_HOST
BACKUP_HOSTNAME = 'localhost'